INSERT INTO PRICE (currency, price, vehicle_id) VALUES ('USD', 1.00, 1),
                                                      ('EUR', 12.00, 2),
                                                      ('PESOS', 6.00, 3),
                                                      ('USD', 9.00, 4),
                                                      ('USD', 352.00, 5),
                                                      ('USD', 567.00, 6),
                                                      ('USD', 3067.00, 7),
                                                      ('EUR', 1074.00, 8),
                                                      ('USD', 952.00, 9),
                                                      ('USD', 4501.00, 10),
                                                      ('PESOS', 105.00, 11),
                                                      ('USD', 16.00, 12);
